### ISSUE TITLE
Normalization of NLL in TPP

### ISSUE THREAD

**Issue by won-bae** [mbilos/neural-flows-experiments#3]
Hi,

I have a question about this line of code (https://github.com/mbilos/neural-flows-experiments/blob/bd19f7c92461e83521e268c1a235ef845a3dd963/nfe/experiments/tpp/experiment.py#L50)
where NLL is normalized with the number of batches instead of the number of samples. Is this a bug? Or Am I missing something here? Thank you.

**Comment by mbilos** [comment]
Whatever metric we wish to compute we would probably want to average it over the batches. Otherwise, you can't compare models trained with different batch sizes.
