### ISSUE TITLE
times variable

### ISSUE THREAD

**Issue by JingWang18** [mbilos/neural-flows-experiments#5]
Hi Authors,

Thanks for sharing the code. When I printed the input variable "times", it always gave me an increasing order. As you mentioned in your paper, you used the inter-event time as the input. So, "times" should not be in a strictly increasing order. Could you please confirm what the input "times" stand for? the inter-event time or the arrival time of an event? 

BTW, when I transformed "times" into inter-event time by getting the time difference between nearby events, I got 3.43 on using Marked TPP on Wiki. Could you please also elaborate on the improvement here?

Huge thanks in advance for your help!

**Comment by mbilos** [comment]
In TPP experiment, times should refer to the difference between consecutive observations, like you said. Synthetic datasets are preprocessed correctly. It seems that wiki might be incorrectly preprocessed. Using delta times should improve the results.

**Comment by JingWang18** [comment]
Thank you authors for the detailed reply. It makes sense to me now.
