### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by randolf-scholz** [mbilos/neural-flows-experiments#6]
Hey, I'd like to re-use some of the pre-processing scripts. Can you please add a `LICENSE`? https://academia.stackexchange.com/questions/142393/use-of-of-unlicensed-github-code-in-research-paper

**Comment by mbilos** [comment]
Preprocessing was adapted from other papers and their respective repositories, we put the links in the README file. The best would be to go to those repositories directly, check the license and reuse the code from there. Our accompanying [library](https://github.com/mbilos/stribor) is under MIT license if you want to replicate the models.
